/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ventas;

import view.compras.*;
import connection.DBConnection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelUniversal;

/**
 *
 * @author gonza
 */
public class Ventas extends javax.swing.JInternalFrame {
    
    ModelUniversal modelUniversal = new ModelUniversal();
    DefaultTableModel tableModel;
    
    static double total = 0.0;
    double sub_total = 0.0;
    double iva = 0.0;
    
    public Ventas() {
        initComponents();
        this.setTitle("Generar Venta");
        
//        txtNitCompras.setEditable(false);
//        txtNombreCompras.setEditable(false);
//        txtDireccionCompras.setEditable(false);
//        txtTelCompras.setEditable(false);
            txtIdProducto.setVisible(false);
        
        jComboBoxTipoDoc.addItem("-Seleccionar-");
//        jComboBoxTipoDoc.addItem("Boleta");
        jComboBoxTipoDoc.addItem("Factura");
        jComboBoxTipoDoc.addItem("Boleta");
        
        jComboFormaPago.addItem("-Seleccionar-");
        jComboFormaPago.addItem("Contado");
        txtIdVenta.setVisible(false);
        txtIdProducto.setVisible(false);
        
        
        btnEditarProducto.setVisible(false);
        btnCancelarProducto.setVisible(false);
        
        
        txtCodigoCompras.setEditable(false);
        txtnombreComprasProducto.setEditable(false);
        txtstockCompras.setEditable(false);
        txtPrecioCompras.setEditable(false);
        txtCantidadCompras.setEditable(false);
        
        txtSubTotal.setEditable(false);
        txtIva.setEditable(false);
        txtTotal.setEditable(false);
        txtNumProductos.setEditable(false);
        
//        numeroCompra();
        
        modelUniversal.ocultarColumnas(tableventas, 5);
        modelUniversal.ocultarColumnas(tableventas, 6);
        modelUniversal.ocultarColumnas(tableventas, 7);
       
//        dobleClickTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupProductos = new javax.swing.ButtonGroup();
        jDialogComprasProveedores = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNitCompras = new javax.swing.JTextField();
        txtNombreCompras = new javax.swing.JTextField();
        txtDireccionCompras = new javax.swing.JTextField();
        txtTelCompras = new javax.swing.JTextField();
        btbBuscarProveedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTipoDoc = new javax.swing.JComboBox<>();
        txtNumDocumentoCompra = new javax.swing.JTextField();
        jComboFormaPago = new javax.swing.JComboBox<>();
        jDateFechaCompra = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtNumCompras = new javax.swing.JTextField();
        txtIdVenta = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoCompras = new javax.swing.JTextField();
        txtnombreComprasProducto = new javax.swing.JTextField();
        txtstockCompras = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrecioCompras = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCantidadCompras = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        btnQuitarProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        txtIdProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableventas = new org.jdesktop.swingx.JXTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNumProductos = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnCancelarCompra = new javax.swing.JButton();
        btnRegistrarCompra = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialogComprasProveedoresLayout = new javax.swing.GroupLayout(jDialogComprasProveedores.getContentPane());
        jDialogComprasProveedores.getContentPane().setLayout(jDialogComprasProveedoresLayout);
        jDialogComprasProveedoresLayout.setHorizontalGroup(
            jDialogComprasProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogComprasProveedoresLayout.setVerticalGroup(
            jDialogComprasProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setText("Nit");

        jLabel10.setText("Nombre:");

        jLabel11.setText("Direccion:");

        jLabel12.setText("Teléfono");

        btbBuscarProveedor.setText("Buscar");
        btbBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBuscarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNitCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btbBuscarProveedor))
                    .addComponent(txtNombreCompras)
                    .addComponent(txtDireccionCompras)
                    .addComponent(txtTelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNitCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbBuscarProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDireccionCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtTelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 380, 170));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Tipo de documento: ");

        jLabel2.setText("Serie /  N. Doc");

        jLabel3.setText("Forma de pago: ");

        jLabel4.setText("Fecha:");

        jDateFechaCompra.setDateFormatString("dd/MM/yyyy");

        jLabel16.setText("Venta No.");

        jLabel25.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNumCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNumDocumentoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumCompras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumDocumentoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateFechaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboFormaPago))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, 170));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setText("Codigo:");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Stock:");

        jLabel8.setText("Precio:");

        txtCodigoCompras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoCompras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoComprasFocusLost(evt);
            }
        });

        txtstockCompras.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField8.setText("jTextField4");

        jLabel13.setText("Cantidad:");

        txtPrecioCompras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Cantidad:");

        txtCantidadCompras.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnQuitarProducto.setText("Quitar");
        btnQuitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProductoActionPerformed(evt);
            }
        });

        btnEditarProducto.setText("Editar");
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });

        btnCancelarProducto.setText("Cancelar");
        btnCancelarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13)
                        .addGap(315, 315, 315)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombreComprasProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitarProducto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtstockCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarProducto)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCodigoCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtnombreComprasProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarProducto)
                        .addComponent(btnAgregarProducto)
                        .addComponent(btnQuitarProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtstockCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtPrecioCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(txtCantidadCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelarProducto)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarProducto)
                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 750, 100));

        tableventas = new org.jdesktop.swingx.JXTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tableventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Precio. Unit.", "Importe", "Stock", "Id Compra", "id Poducto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableventas.setFocusable(false);
        jScrollPane1.setViewportView(tableventas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 750, 140));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Sub Total:");

        txtSubTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("IVA:");

        txtIva.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Total:");

        txtTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 51, 51));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel22.setText("productos agregados");

        txtNumProductos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel22))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txtNumProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 750, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnCancelarCompra.setText("Cancelar");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        btnRegistrarCompra.setText("Registar Venta");
        btnRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCompraActionPerformed(evt);
            }
        });

        jCheckBox1.setText("I.V.A: 12% ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(btnRegistrarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarCompra)
                .addGap(24, 24, 24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelarCompra)
                        .addComponent(btnRegistrarCompra))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 750, 50));

        jLabel17.setText("Datos Cliente");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel23.setText("Documento");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel24.setText("Datos Producto");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarProveedorActionPerformed
//        abrirJDialogProveedores();
    }//GEN-LAST:event_btbBuscarProveedorActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        
//        abrirJDialogProductos();
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
//        if (txtCodigoCompras.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Seleccione un producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
//            btnBuscarProducto.requestFocus();
//        }else if (txtCantidadCompras.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Ingrese cantidad", "Advertencia", JOptionPane.WARNING_MESSAGE);
//            txtCantidadCompras.requestFocus();
//        }else {
//            agregarProductoTabla();
//            txtCodigoCompras.setText("");
//            txtnombreComprasProducto.setText("");
//            txtstockCompras.setText("");
//            txtPrecioCompras.setText("");
//            txtCantidadCompras.setText("");
//            
//            txtPrecioCompras.setEditable(false);
//            txtCantidadCompras.setEditable(false);
//            btnCancelarProducto.setVisible(false);
//        }     
    }//GEN-LAST:event_btnAgregarProductoActionPerformed
    
    private void btnQuitarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarProductoActionPerformed
//        quitarProducto();
//        txtCodigoCompras.setText("");
//        txtnombreComprasProducto.setText("");
//        txtstockCompras.setText("");
//        txtPrecioCompras.setText("");
//        txtCantidadCompras.setText("");
//        
//        btnEditarProducto.setVisible(false);
//        btnCancelarProducto.setVisible(false);
//        btnAgregarProducto.setEnabled(true);
        
    }//GEN-LAST:event_btnQuitarProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
//        editarProducto();
//        txtCodigoCompras.setText("");
//        txtnombreComprasProducto.setText("");
//        txtstockCompras.setText("");
//        txtPrecioCompras.setText("");
//        txtCantidadCompras.setText("");
//        
//        btnEditarProducto.setVisible(false);
//        btnCancelarProducto.setVisible(false);       
//        btnAgregarProducto.setEnabled(true);
//        
//        btnBuscarProducto.requestFocus();
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
        total = 0.0;
        sub_total = 0.0;
        iva = 0.0;
        this.dispose();
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    private void txtCodigoComprasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoComprasFocusLost
        
    }//GEN-LAST:event_txtCodigoComprasFocusLost

    private void btnCancelarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProductoActionPerformed
//        txtCodigoCompras.setText("");
//        txtnombreComprasProducto.setText("");
//        txtstockCompras.setText("");
//        txtPrecioCompras.setText("");
//        txtCantidadCompras.setText("");
//        
//        txtPrecioCompras.setEditable(false);
//        txtCantidadCompras.setEditable(false);
//        
//        btnEditarProducto.setVisible(false);
//        btnCancelarProducto.setVisible(false);
//        
//        btnBuscarProducto.requestFocus();
//        
//        btnAgregarProducto.setEnabled(true);
    }//GEN-LAST:event_btnCancelarProductoActionPerformed

    private void btnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCompraActionPerformed
//      registrarDetalleCompra();
    }//GEN-LAST:event_btnRegistrarCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbBuscarProveedor;
    private javax.swing.JButton btnAgregarProducto;
    public static javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCancelarCompra;
    public static javax.swing.JButton btnCancelarProducto;
    public static javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JButton btnRegistrarCompra;
    private javax.swing.ButtonGroup buttonGroupProductos;
    private javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JComboBox<String> jComboBoxTipoDoc;
    public static javax.swing.JComboBox<String> jComboFormaPago;
    public static com.toedter.calendar.JDateChooser jDateFechaCompra;
    public static javax.swing.JDialog jDialogComprasProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField8;
    public static org.jdesktop.swingx.JXTable tableventas;
    public static javax.swing.JTextField txtCantidadCompras;
    public static javax.swing.JTextField txtCodigoCompras;
    public static javax.swing.JTextField txtDireccionCompras;
    public static javax.swing.JTextField txtIdProducto;
    public static javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtIva;
    public static javax.swing.JTextField txtNitCompras;
    public static javax.swing.JTextField txtNombreCompras;
    public static javax.swing.JTextField txtNumCompras;
    public static javax.swing.JTextField txtNumDocumentoCompra;
    private javax.swing.JTextField txtNumProductos;
    public static javax.swing.JTextField txtPrecioCompras;
    private javax.swing.JTextField txtSubTotal;
    public static javax.swing.JTextField txtTelCompras;
    private javax.swing.JTextField txtTotal;
    public static javax.swing.JTextField txtnombreComprasProducto;
    public static javax.swing.JTextField txtstockCompras;
    // End of variables declaration//GEN-END:variables

 /*   private void abrirJDialogProveedores() {        
        (new DialogBuscarProveedor(jDialogComprasProveedores, true)).setVisible(true);
    }
    
    private void abrirJDialogProductos() {
        (new DialogBuscarProducto(jDialogComprasProveedores, true)).setVisible(true);
    }
    
    private void agregarProductoTabla() {
        tableModel = (DefaultTableModel) tableCompras.getModel();
        String codigo = txtCodigoCompras.getText();
        String nombre = txtnombreComprasProducto.getText();
        String cantidad = txtCantidadCompras.getText();
        String precio = txtPrecioCompras.getText();
        String stock = txtstockCompras.getText();
        String idCompra = txtIdCompra.getText();
        String idProdcuto = txtIdProducto.getText();
        
        int cant = Integer.parseInt(cantidad);
        double prec = Double.parseDouble(precio);
        double importe = cant * prec;
        
        Object fila[] = new Object[8];
        
        fila[0] = codigo;
        fila[1] = nombre;
        fila[2] = cantidad;
        fila[3] = precio;
        fila[4] = importe;
        fila[5] = stock;
        fila[6] = idCompra;
        fila[7] = idProdcuto;
        tableModel.addRow(fila);        
        tableCompras.setModel(tableModel);

        // double calcula = importe;
        total = total + importe;
        iva = total * 0.12;
        sub_total = total - iva;
        
        txtSubTotal.setText("" + sub_total);
        txtIva.setText("" + iva);
        txtTotal.setText("" + total);        
        
        txtNumProductos.setText("" + modelUniversal.numeroDatosTabla(tableCompras));
    }
    
    private void quitarProducto() {
        tableModel = (DefaultTableModel) tableCompras.getModel();
        
        double totalActua = 0.0;
        double ivaActual = 0.0;
        double subTotalActual = 0.0;
        double importe = 0.0;
        
        int fila = tableCompras.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este producto?", "Eliminar", JOptionPane.YES_NO_OPTION);
            if (confirmar == JOptionPane.YES_OPTION) {
                
                importe = Double.parseDouble(tableCompras.getValueAt(fila, 4).toString());
                totalActua = Double.parseDouble(txtTotal.getText()) - importe;
                total = totalActua;
                
                ivaActual = total * 0.12;
                
                subTotalActual = totalActua - ivaActual;
                
                txtSubTotal.setText("" + subTotalActual);
                txtIva.setText("" + ivaActual);
                txtTotal.setText("" + total);
                
                tableModel.removeRow(fila);
            }
        }
        txtNumProductos.setText("" + modelUniversal.numeroDatosTabla(tableCompras));
    }

    /*   private void editarProducto(){
        tableModel = (DefaultTableModel) tableCompras.getModel();
        int fila = tableCompras.getSelectedRow();
        String cantidad = txtCantidadCompras.getText();       
        
        tableModel.setValueAt(cantidad, fila, 2);      //actualiza la cantidad    
    }*
    private void editarProducto() {
        tableModel = (DefaultTableModel) tableCompras.getModel();
        double totalActua = Double.parseDouble(txtTotal.getText().toString());
        double ivaActual = 0.0;
        double subTotalActual = 0.0;
        
        double importe_nuevo = 0.0;
        
        int fila = tableCompras.getSelectedRow();
        
        double importe_actual = Double.parseDouble(tableCompras.getValueAt(fila, 4).toString());
        int cantidad_actual = Integer.parseInt(tableCompras.getValueAt(fila, 2).toString());
        int cantidad_nueva = Integer.parseInt(txtCantidadCompras.getText());
        double precio_actual = Double.parseDouble(tableCompras.getValueAt(fila, 3).toString());
        double precio_nuevo = Double.parseDouble(txtPrecioCompras.getText().toString());
        
        if (cantidad_nueva != cantidad_actual || precio_nuevo != precio_actual) {
            
            importe_nuevo = cantidad_nueva * precio_nuevo;
            
            tableModel.setValueAt(cantidad_nueva, fila, 2);
            tableModel.setValueAt(precio_nuevo,fila,3);
            tableModel.setValueAt(importe_nuevo, fila, 4);
            
            totalActua = totalActua - importe_actual;
            
            total = totalActua + importe_nuevo;
            
            ivaActual = total * 0.12;
            
            subTotalActual = total - ivaActual;
            
            txtSubTotal.setText("" + subTotalActual);
            txtIva.setText("" + ivaActual);
            txtTotal.setText("" + total);
        } else {
            //JOptionPane.showMessageDialog(null, "Ingrese una cantidad diferente!","Error",JOptionPane.ERROR_MESSAGE);
            txtCodigoCompras.setText("");
            txtnombreComprasProducto.setText("");
            txtstockCompras.setText("");
            txtPrecioCompras.setText("");
            txtCantidadCompras.setText("");
            
            txtPrecioCompras.setEditable(false);
            txtCantidadCompras.setEditable(false);
            
            btnCancelarProducto.setVisible(false);
            btnEditarProducto.setVisible(false);
        }
    }
    
    public final void dobleClickTabla() {
        
        tableCompras.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    //System.err.println("Dos clicks");

                    int fila = tableCompras.getSelectedRow();
                    // System.err.println("fila: " + fila);
                    txtCodigoCompras.setText(tableCompras.getValueAt(fila, 0).toString());
                    txtnombreComprasProducto.setText(tableCompras.getValueAt(fila, 1).toString());
                    txtstockCompras.setText(tableCompras.getValueAt(fila, 5).toString());
                    txtPrecioCompras.setText(tableCompras.getValueAt(fila, 3).toString());
                    txtCantidadCompras.setText(tableCompras.getValueAt(fila, 2).toString());
                    
                    
                    txtPrecioCompras.setEditable(true);
                    txtCantidadCompras.setEditable(true);
                    
                    btnEditarProducto.setVisible(true);
                    btnCancelarProducto.setVisible(true);
                    
                    txtCantidadCompras.requestFocus();
                    
                    btnAgregarProducto.setEnabled(false);
                }
            }
        });
    }    
    
    private void numeroCompra() {
        DBConnection dBConnection = new DBConnection();
        String querty = "SELECT * FROM relopsa.compras";

        int numCompra = 0;
        String datos[] = new String[1];
        int count = 0;

        try {
            Statement st = dBConnection.connetion().createStatement();
            ResultSet rs = st.executeQuery(querty);

            if (!rs.next()) {
                txtNumCompras.setText("1");
            } else {
                
               do{
                   datos[0] = rs.getString(4);
               }while (rs.next());

                numCompra = Integer.parseInt(datos[0]) + 1;
                txtNumCompras.setText("" + numCompra);
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
            //   JOptionPane.showMessageDialog(null, "Insercion no exitosa!");
        } finally {
            try {
                dBConnection.closeConnection();
                System.err.println("Conexion cerrada");
            } catch (SQLException ex) {
                Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void registrarDetalleCompra() {
        DBConnection conRegistrar = new DBConnection();
        String querty = "INSERT INTO detalleCompra (cantidad, precio_compra, compras_id, productos_id) VALUES (?,?,?,?)";
        try {
            PreparedStatement statement = conRegistrar.connetion().prepareStatement(querty);
            
            for (int i = 0; i < tableCompras.getRowCount(); i++) {
                
                statement.setInt(1, Integer.parseInt(tableCompras.getValueAt(i, 2).toString()));
                statement.setDouble(2, Double.parseDouble(tableCompras.getValueAt(i, 3).toString()));
                statement.setInt(3, Integer.parseInt(tableCompras.getValueAt(i, 6).toString()));
                statement.setInt(4, Integer.parseInt(tableCompras.getValueAt(i, 7).toString()));  
                statement.executeUpdate();
            }
           
            JOptionPane.showMessageDialog(null, "Ingresado Correctamente!");
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage() + ex);
                JOptionPane.showMessageDialog(null, "Insercion no exitosa!", "Error", JOptionPane.ERROR);
        }finally {
                try {
                    conRegistrar.closeConnection();
                    System.err.println("Conexion generar compras cerrada");
                } catch (SQLException ex) {
                    System.err.println(ex);
                   Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }*/
}